CREATE DATABASE "Analisis2026";

CREATE TABLE IF NOT EXISTS rol (
  "Id_Rol" SERIAL PRIMARY KEY,
  "Rol" VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
  "Id" SERIAL PRIMARY KEY,
  "Usuario" VARCHAR(50) NOT NULL UNIQUE,
  "Nombre" VARCHAR(250) NOT NULL,
  "Password" VARCHAR(255) NOT NULL,
  "Id_Rol" INT NOT NULL,
  "Correo" VARCHAR(150) NOT NULL UNIQUE,
  "Telefono" VARCHAR(20) NOT NULL,
  CONSTRAINT "FK_Usuarios_Rol" FOREIGN KEY ("Id_Rol")
    REFERENCES rol("Id_Rol")
);

INSERT INTO rol ("Rol") VALUES ('admin') ON CONFLICT DO NOTHING;
INSERT INTO rol ("Rol") VALUES ('usuario') ON CONFLICT DO NOTHING;